### ISSUE TITLE
Añadir sección "Colchón de seguridad"

### ISSUE THREAD

**Issue by fnandot** [victor-marino/indexax#53]
El dinero invertido en "Colchón de seguridad" no aparece en la sección "Cartera". Y, además, aparece como "Otros" en la sección "Distribución".

**Comment by victor-marino** [comment]
Gracias! No tengo fondo de emergencia en mi cuenta así que desconozco los campos que devuelve la API para poder mapearlos y mostrarlos correctamente. Como Indexa no ofrece cuentas de prueba ni tampoco muestran payloads de ejemplo, sólo conozco lo que devuelve mi propia cuenta.

Lo comentaré en el grupo oficial de la API, a ver si me aclaran cómo es el payload.

**Comment by fnandot** [comment]
¡Grande! justo te iba a comentar si necesitabas datos te podía pasar mi respuesta de la API anonimizada pero ya veo que te lo han pasado por el grupo de Telegram 😉.

Muchas gracias, esta quedando muy bien la App 👌.

**Comment by victor-marino** [comment]
Hola @fnandot.

Justo te estaba escribiendo 😄

Acabo de enviar nueva versión (1.6.5) tanto al Play Store como al App Store que añade soporte para el colchón de seguridad. En cuanto Google o Apple den la aprobación debería saltarte la actualización.

He hecho mis pruebas simulando los datos del fondo monetario en local, pero te agradecería si una vez la pruebes tú me pudieras confirmar que no hay ningún bug por ahí 😉

Gracias a ti por avisar!
