### ISSUE TITLE
Añadir opción para ocultar las cantidades monetarias en todas las pantallas

### ISSUE THREAD

**Issue by mmosquera91** [victor-marino/indexax#57]
Tal y como la app oficial, sería bastante útil poder ocultar los montos pero que los porcentajes se mantengan visibles

**Comment by victor-marino** [comment]
Muchas gracias por la sugerencia @mmosquera91. Estoy de acuerdo.

Voy a implementar un switch global en la parte superior de la app que oculte todas las cantidades monetarias en todas las pantallas.

Espero tenerlo listo en unos días 😉

**Comment by victor-marino** [comment]
Hecho!

La actualización está bajo revisión tanto en el Play Store como en el App Store, así que te llegará en cuanto la aprueben ;-)

**Comment by mmosquera91** [comment]
Gracias por la rapidez @victor-marino crack!! Ya recibí la actualización 😁
