### ISSUE TITLE
Mover opción de modo privado al menú contextual de opciones

### ISSUE THREAD

**Issue by victor-marino** [victor-marino/indexax#63]

**Comment by mmosquera91** [comment]
Hola @victor-marino. Una nota sobre este feature: el texto "modo privado" es estático y no cambia con respecto al idioma del movil

**Comment by victor-marino** [comment]
Gracias @mmosquera91! Típico descuido del que no me hubiese dado cuenta nunca 😄

Corregido y actualización enviada al Play Store, en un rato debería estar publicada.
